duoServer: true

players:
  Notch: 1
finished:
  Notch: 10910

commandsToExecute:
  - 'say %player% has killed an ender dragon. %player% is awesome!'
commandsToExecuteOnReset:
  - 'say %player% timer has been reset by a mysterious creature!'